/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xian_myapp_jni_JNIControl */

#ifndef _Included_com_xian_myapp_jni_JNIControl
#define _Included_com_xian_myapp_jni_JNIControl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xian_myapp_jni_JNIControl
 * Method:    stringFromJNI
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xian_myapp_jni_JNIControl_stringFromJNI
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_xian_myapp_jni_JNIControl
 * Method:    stringFromJNILongTime
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xian_myapp_jni_JNIControl_stringFromJNILongTime
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
